# Site settings
title: SavvySuit Fine Print
email: writetous@savvysuit.com
description: > # this means to ignore newlines until "baseurl:"
  We're lawyers who work with lawyers... there's going to be fine print.
  Our terms of use, privacy policy, and open source attributions here for your perusal.
  Check back soon, we'll  be adding more information soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fineprint.savvysuit.com" # the base hostname & protocol for your site
twitter_username: savvysuit

# Build settings
markdown: kramdown
